version: '3.8'
services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   volumes:
     - ./:/src
     - yarn_cache:/usr/local/share/.cache/yarn/v6:cached
   command: sh -c "npm run dev"
   ports:
     - "3000:3000"
   stdin_open: true

volumes:
  node_modules:
  yarn_cache: